receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
  # Reads local JSON log files and ships them as OTLP logs.
  filelog:
    include: ["${env:APP_LOG_PATH}"]
    start_at: beginning
    operators:
      - type: json_parser
        parse_from: body

processors:
  batch: {}

exporters:
  otlphttp:
    # Replace <SIGNOZ_REGION> with your SigNoz Cloud region (e.g., us, eu, in)
    endpoint: ingest.<SIGNOZ_REGION>.signoz.cloud:443
    tls:
      insecure: false
    headers:
      # Replace <YOUR_SIGNOZ_INGESTION_KEY> with the key from the SigNoz Cloud UI.
      signoz-ingestion-key: "<YOUR_SIGNOZ_INGESTION_KEY>"
  debug:
    verbosity: normal

extensions:
  health_check: {}
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    logs:
      level: debug
      encoding: console

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp, debug]

    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [otlphttp, debug]
